# Generated by Django 3.0.8 on 2020-07-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('salt', models.CharField(max_length=128)),
                ('hashed_password', models.CharField(max_length=400)),
            ],
        ),
    ]
