# Generated by Django 3.0.8 on 2020-07-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='payload',
            field=models.TextField(default=None),
        ),
    ]
