# Generated by Django 3.0.8 on 2020-07-17 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_attempt_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='sqliAttempt',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Attempt')),
            ],
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='sessionid',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='upgrade_insecure_request',
        ),
        migrations.AddField(
            model_name='attempt',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='method',
            field=models.CharField(default='POST', max_length=15),
        ),
        migrations.AddField(
            model_name='attempt',
            name='query_string',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='server_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attempt',
            name='server_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='accept',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='accept_encoding',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='accept_language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='content_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='content_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='cookie',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='host',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='ip',
            field=models.GenericIPAddressField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='referer',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_agent',
            field=models.CharField(default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
