# Generated by Django 3.0.8 on 2020-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_userpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpass',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
