# Generated by Django 3.0.8 on 2020-07-17 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_userpass_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlInjection',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Attempt')),
            ],
        ),
        migrations.DeleteModel(
            name='sqliAttempt',
        ),
    ]
