# Generated by Django 3.0.8 on 2020-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200717_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='accept_encoding',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
