# Generated by Django 3.0.8 on 2020-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20200717_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpass',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
