# Generated by Django 3.0.8 on 2020-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200717_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='sql_injdection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sqlinjection',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='sqlinjection',
            name='payload',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
