# Generated by Django 3.0.8 on 2020-07-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_passwords_usernames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='sql_injdection',
        ),
    ]
