# Generated by Django 3.0.8 on 2020-07-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_attempt_sql_injdection'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='sql_injection',
            field=models.BooleanField(default=False),
        ),
    ]
