# Generated by Django 3.0.8 on 2020-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_attempt_sql_injection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlinjection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
