# Generated by Django 3.0.8 on 2020-07-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20200717_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlinjection',
            name='id',
        ),
        migrations.AddField(
            model_name='sqlinjection',
            name='attempt',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Attempt'),
        ),
    ]
